GET http://localhost:777/alimentos 




###




POST http://localhost:777/alimentos 
Content-Type: application/json


{
    "nome": "Arroz",
    "peso": "100g",
    "ptn": 4.42, 
    "carb": 28, 
    "fat": 1.68,
    "kcal": 144.8
}





### 



PUT http://localhost:777/alimentos 
Content-Type: application/json







###




DELETE  http://localhost:777/alimentos 



